create table
  public.cart_ids (
    cart_id integer generated by default as identity,
    customer text not null,
    constraint cart_ids_pkey primary key (cart_id),
    constraint cart_ids_cart_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_id integer generated by default as identity,
    potion_id integer not null,
    quantity integer null default 0,
    constraint cart_items_pkey primary key (cart_id, potion_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references cart_ids (cart_id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion (potion_id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    num_red_ml integer not null,
    gold integer null,
    num_blue_ml integer null default 0,
    num_green_ml integer null default 0,
    num_dark_ml integer null default 0
  ) tablespace pg_default;

create table
  public.potion (
    potion_id integer generated by default as identity,
    sku text not null,
    name text null,
    quantity integer null default 0,
    cost integer null default 0,
    red_ml integer null default 0,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    dark_ml integer null default 0,
    potion_type integer[] null default '{0,0,0,0}'::integer[],
    constraint potion_pkey primary key (potion_id)
  ) tablespace pg_default;

