create table
  public.cart_ids (
    cart_id integer generated by default as identity,
    customer text not null,
    constraint cart_ids_pkey primary key (cart_id),
    constraint cart_ids_cart_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.customer_orders_ledger (
    id bigint generated by default as identity,
    timestamp timestamp with time zone not null default now(),
    cart_id bigint null,
    potion_id bigint null,
    quantity bigint null default '0'::bigint,
    constraint customer_orders_ledger_pkey primary key (id),
    constraint customer_orders_ledger_cart_id_fkey foreign key (cart_id) references cart_ids (cart_id),
    constraint customer_orders_ledger_potion_id_fkey foreign key (potion_id) references potion_types (potion_id)
  ) tablespace pg_default;

create table
  public.gold_ledger (
    id bigint generated by default as identity,
    timestamp timestamp with time zone not null default now(),
    entry text null,
    change bigint null default '0'::bigint,
    description text null,
    constraint gold_ledger_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.ml_ledger (
    id bigint generated by default as identity,
    timestamp timestamp with time zone not null default now(),
    color text null,
    entry text null,
    change bigint null default '0'::bigint,
    description text null,
    constraint ml_ledger_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_ledger (
    id bigint generated by default as identity,
    timestamp timestamp with time zone not null default now(),
    entry text null,
    potion_id bigint null,
    change bigint null default '0'::bigint,
    description text null,
    constraint potion_ledger_pkey primary key (id),
    constraint potion_ledger_potion_id_fkey foreign key (potion_id) references potion_types (potion_id)
  ) tablespace pg_default;

create table
  public.potion_types (
    potion_id bigint generated by default as identity,
    sku text not null,
    name text null,
    cost bigint null default '0'::bigint,
    red_ml bigint null default '0'::bigint,
    green_ml bigint null default '0'::bigint,
    blue_ml bigint null default '0'::bigint,
    dark_ml bigint null default '0'::bigint,
    constraint potion_types_pkey primary key (potion_id)
  ) tablespace pg_default;